version: '3.1'

services:
  sampleshinyapp:
    build: app/.
    expose:
      - 3838
    networks:
      - selenium-grid

  hub:
    image: selenium/hub:3.14.0
    expose:
      - 4444
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome-debug:3.14.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5901:5901
    depends_on:
      - hub
    networks:
      - selenium-grid


  test-gc:
    build: robot
    command: --outputdir /tests/out/ --timestampoutputs tests
    depends_on:
      - sampleshinyapp
      - chrome
    networks:
      - selenium-grid

networks:
  selenium-grid: