version: '3.1'

services:
  sampleshinyapp:
    container_name: sampleshinyapp
    image: kshitijsrivastava/shinytravisci:1
    expose:
      - 3838
    networks:
      - selenium-grid

  hub:
    container_name: hub
    image: selenium/hub:3.14.0
    expose:
      - 4444
    networks:
      - selenium-grid

  chrome:
    container_name: chrome
    image: selenium/node-chrome:3.14.0
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    networks:
      - selenium-grid


  test-gc:
    container_name: test-gc
    build: robot
    command: --outputdir /tests/out/ --timestampoutputs tests
    depends_on:
      - sampleshinyapp
      - chrome
    networks:
      - selenium-grid

networks:
  selenium-grid:
