version: '3.1'

services:
  sampleshinyapp:
    image: kshitijsrivastava/shinytravisci:2
    expose:
      - 3838
    networks:
      - selenium-grid

  hub:
    image: selenium/hub
    expose:
      - 4444
    networks:
      - selenium-grid
    healthcheck:
      test: curl -f -s http://localhost:4444/wd/hub || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3


  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    networks:
      - selenium-grid
    ports:
      - 5555

  test-gc:
    networks:
      - selenium-grid
    command: --outputdir /tests/out/ --timestampoutputs tests
    depends_on:
      - hub
      - sampleshinyapp
      - chrome
    build: robot
    
networks:
  selenium-grid:
    driver: bridge
