#!/bin/sh

sudo su - -c "R -q -e \"install.packages('reshape2', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('grDevices', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('devtools', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"require(devtools)\""
sudo su - -c "R -q -e \"devtools::install_version('ggplot2', version = '2.2.1', repos = 'http://cran.us.r-project.org')\""
sudo su - -c "R -q -e \"install.packages('stringr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('lubridate', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('gridExtra', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('shinydashboard', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('shinyBS', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('shinyjs', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('tidyr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('scales', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('rJava', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('mailR', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('log4r', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('zoo', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('knitr', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('AER', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('caret', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('DT', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('lattice', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('RColorBrewer', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('maptools', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('rgdal', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('shapefiles', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('xtable', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('flexclust', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('corrplot', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('markdown', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('gtable', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('properties', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('googleVis', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('ggthemes', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('plotly', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('sendmailR', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('Hmisc', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('doParallel', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('gbm', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('h2o', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('xlsx', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('DataExplorer', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('sqldf', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('rio', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('RODBC', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('bsplus', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('ggExtra', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('ggvis', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('leaflet', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('rgdal', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('rgeos', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('sp', repos='http://cran.rstudio.com/')\""
#sudo su - -c "R -q -e \"devtools::install_github('jcheng5/bubbles')\""
sudo su - -c "R -q -e \"install.packages('data.table', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('kableExtra', repos='http://cran.rstudio.com/')\""
sudo su - -c "R -q -e \"install.packages('shinyWidgets', repos='http://cran.rstudio.com/')\""
